### ISSUE TITLE
Card linking is mondatory?

### ISSUE THREAD

**Issue by bsde1234** [google-pay/gpay-live-demo#1]
I linked my bank account in gpay. But when clicking payment button it says no card linked. Does card link is mondatory?

**Comment by socsieng** [comment]
Can you clarify what you mean by _bank account_?

Technically bank accounts won't appear in Google Pay but credit and debit cards will.

**Comment by bsde1234** [comment]
![Screenshot_20201104-173920](https://user-images.githubusercontent.com/35421561/98188333-d78e7800-1f38-11eb-9f81-fffd0855eeeb.png)
I am from India. Here we don't need to add card to use gpay.

**Comment by socsieng** [comment]
How do you bring up that screen? Does that happen when you click on the Google Pay button?

With Google Pay, the developer/merchant specifies which payment methods they accept and the Google Pay sheet will usually display a list of payment methods that a user has that can fulfill the payment. Bank account is not a supported payment method. 

If you are in India, a common payment method is UPI. Check out https://developers.google.com/pay/india/api/web/intro

**Comment by bsde1234** [comment]
That screen is from gpay android app in profile>payment methods. We dont use any card in gpay transactions. How a customer should buy using your button with gpay app. May be I misunderstoud this project. Can I purchase with app or not? We have upi id like mobilenumber@upi username@oksbi. any use fot it instead card?

![Screenshot_20201105-141720](https://user-images.githubusercontent.com/35421561/98218415-be55ed80-1f71-11eb-9ded-a812865ccdae.png)

**Comment by bsde1234** [comment]
So when I click your payment button why it is not asking for upi Id instead of card. Where I can set to ask upi id in program

**Comment by bsde1234** [comment]
Any help appreciated

**Comment by socsieng** [comment]
In your web application, you should request a UPI payment. The user can then complete the UPI payment with a supported UPI app installed on their device (Google Pay being one of the supported apps).

You can request a UPI payment with the [PaymentRequest API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API). The Google Pay developer documentation has a [tutorial](https://developers.google.com/pay/india/api/web/create-payment-method) that you can follow. Please try it out to see if it meets your requirements.

**Comment by bsde1234** [comment]
Thanks, closing for now. If possible make a demo project.
